pop-os/system76-firmware

- Cargo.toml
- Makefile
- debian/system76-firmware.install
> Rename cli binary to have -cli suffix

- Cargo.lock
- Cargo.toml
- debian/control
- examples/thelio_io.rs
- src/bin/cli.rs
- src/bin/daemon.rs
- src/config.rs
- src/lib.rs
- src/thelio_io.rs
This is still a WIP. It will add support for firmware updates for Thelio Io boards.
> Thelio Io firmware update support

- Cargo.lock
- Cargo.toml
- daemon/Cargo.toml
- daemon/src/lib.rs
- daemon/src/main.rs
- debian/changelog
- src/lib.rs
Will tag a new release when this is merged
> 1.0.8 - meer5 support

- Cargo.lock
- Cargo.toml
- debian/changelog
- src/ec.rs
- src/lib.rs
This will detect System76 EC's and return the model and version information if applicable
> Add support for system76-ec

- Cargo.lock
- Cargo.toml
- debian/changelog
- src/lib.rs
> 1.0.10 - add serw12 and thelio-r2

- debian/changelog
- src/lib.rs
> 1.0.11 - add addw2 and gaze15

- Cargo.toml
- debian/changelog
- src/lib.rs
> 1.0.13 - Add oryp6

- Cargo.lock
- Cargo.toml
- debian/changelog
- src/lib.rs
> 1.0.14 - Add bonw14

- Cargo.lock
- Cargo.toml
- debian/changelog
- src/lib.rs
> 1.0.15 - Add thelio-major-r2.1 and thelio-mega-r1.1

- Makefile
- debian/rules
This should fix intermittent build issues
> Sync packaging with system76-power

- .gitignore
- Makefile
> Also vendor daemon crates

- Cargo.lock
- Cargo.toml
- daemon/src/main.rs
- debian/changelog
- src/ec.rs
- Update ectool to ensure locked EC access
- Test that DMI vendor contains System76
Rebase and tag when approved
> 1.0.19 - Update ectool, test DMI vendor

- Cargo.lock
- Cargo.toml
- debian/changelog
- src/lib.rs
> 1.0.21 - Add darp7

- Cargo.lock
- Cargo.toml
- debian/changelog
- src/lib.rs
> 1.0.22 - Add thelio-major-b3

- Cargo.lock
- Cargo.toml
- daemon/Cargo.toml
- daemon/src/lib.rs
- daemon/src/main.rs
- src/lib.rs
- src/thelio_io.rs
- src/util.rs
- Attempts to download firmware up to three times before bailing
- And update the daemon to use DBus 0.9 with its Crossroads API.
> On error, refetch the cached tail block

- Cargo.lock
- Cargo.toml
- debian/changelog
- src/lib.rs
Enable automatic updates for both gaze16 variants.
> Add gaze16

- src/lib.rs
> fix: Reinstate timestamp-based block caching

- Cargo.lock
- Cargo.toml
- debian/changelog
- src/lib.rs
> 1.0.32: Add gaze16-3060-b

- daemon/src/lib.rs
I'm adding a `date` field for each release.
> Handle date field in changelog

- daemon/src/main.rs
- debian/control
- rust-toolchain.toml
- src/bin/cli.rs
We'll eventually need to do firmware updates for Astra using this.
> Build for arm64

- Cargo.lock
- Cargo.toml
- debian/changelog
- src/ec.rs
Fixes: 5d10fb37dba0 ("Add pang15 and bump version to 1.0.64")
> ec: Add pang15

- Cargo.lock
- Cargo.toml
- debian/changelog
- src/config.rs
> 1.0.68: update public key

- Cargo.lock
- Cargo.toml
- debian/changelog
- src/lib.rs
add thelio-mega-r4 to `src/lib.rs` MODEL_WHITELIST
> thelio-mega-r4
